apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzV0YVdzNloybDBhSFZpWDNCaGRGOHhNVUZDUzFGR1Zsa3dTMnhYVFZjeFkzRjJNWGxGWDBOVFJVRTNkRFZvY1RKSVN6ZEdkbG81U201a1MzbFlSa2hVY0daeWIxY3dkWEUyYUhwcU0waGxWVzlHTlZaQlIxbzFXbXBGWVd4dE9HcDYiCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
