apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: movies-service-dr
  namespace: cinemaabyss
spec:
  host: movies-service
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8081
      connectionPool:
        http:
          http2MaxRequests: 500
          maxRequestsPerConnection: 5
      outlierDetection:
        consecutive5xxErrors: 3
        interval: 2m
        baseEjectionTime: 30s
        maxEjectionPercent: 50